# Pin npm packages by running ./bin/importmap
# config/importmap.rb

# pin "application", preload: true
# pin "calculate_price", to: "calculate_price.js"
pin "jquery" # @3.7.1
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"

# guide of stimulus
# // This file is auto-generated by ./bin/rails stimulus:manifest:update
# // Run that command whenever you add a new controller or create them with
# // ./bin/rails generate stimulus controllerName